finally passed CRAN auto checks

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,18 +1,13 @@
-#!/usr/bin/env sh
+#!/bin/sh
 
-# adapted from https://github.com/tidyverse/purrr/blob/main/configure
-
-# Check that this is not just ./configure. We need to run this
-# from R CMD INSTALL, to have the R env vars set.
-
+# Fail if not run by R CMD INSTALL
 if [ -z "$R_HOME" ]; then
-echo >&2 R_HOME is not set, are you running R CMD INSTALL?
-exit 1
+  echo >&2 "R_HOME is not set. Are you running this via R CMD INSTALL?"
+  exit 1
 fi
 
-# Find the R binary we need to use. This is a bit trickier on
-# Windows, because it has two architectures. On windows R_ARCH_BIN
-# is set, so this should work everywhere.
-RBIN="${R_HOME}/bin${R_ARCH_BIN}/R"
+# Use Rscript, not R
+R_SCRIPT="${R_HOME}/bin${R_ARCH_BIN}/Rscript"
 
-"$RBIN" --vanilla --slave -f tools/configure.R
+# Run the actual configure logic
+exec "$R_SCRIPT" --vanilla --slave -e "source('tools/configure.R')"
